### ISSUE TITLE
NoSuchField error on servers.

### ISSUE THREAD

**Issue by darkshadow1809** [superdextor/Ad-Inferos-Mod#3]
1.11.2 V1.2.6
Adinferos crashes the server on startup. In the client however it does not happen.

Uploaded both logs related.

[latest.txt](https://github.com/superdextor/Ad-Inferos-Mod/files/1110611/latest.txt)

[crash-2017-06-29_02.53.50-server.txt](https://github.com/superdextor/Ad-Inferos-Mod/files/1110609/crash-2017-06-29_02.53.50-server.txt)

**Comment by superdextor** [comment]
This error has already been reported [here](https://github.com/superdextor/Ad-Inferos-Mod/issues/2).
