### ISSUE TITLE
[1.10.2] - randomly crash due to world generation 

### ISSUE THREAD

**Issue by runescapejon** [superdextor/Ad-Inferos-Mod#4]
Hello i was making a private modpack with me and few friends and we keep on randomly crashing mind fixing it for 1.10.2
https://pastebin.com/VTGuFagg

**Comment by superdextor** [comment]
Before I begin for the future please include the version of Ad Inferos and detailed description I cannot infer anything from "randomly crashing".

I no longer make patches for Minecraft 1.10.2, one day I'll upload the source for 1.10.2 so you may modify it for **PERSON USE ONLY**. Also note I never test my releases on Sponge servers, if you can run a plain Forge Server instead you shouldn't have any problems with Ad Inferos.

**Comment by runescapejon** [comment]
hm the version in the crash report and detail of the crash it's literally in the title 
version: 1.2.4 
just randomly crash cause of world generations but i will test it to see if it's a compatible issue with sponge 
anyways thanks you <3

**Comment by superdextor** [comment]
mhm, you seem down like a down to earth person so I'll give you my reason why I like the version number included. When It comes to bug reports I like to speed read thru them (I'm a little short on time for these projects lately), so it would be very helpful for the future. ;-)

Also I am aware of the crash report description; It's proven to be very helpful to me, however hearing what the player(s) where doing before the error is still valuable information, such as: just after existing a Portal, when creating a World or using a special World-Type/Generator/Seed, etc.. It's just a nice thing to include.

~_The more you know_..
