### ISSUE TITLE
Config option to turn off fire resistance for the player.

### ISSUE THREAD

**Issue by dmodoomsirius** [superdextor/Ad-Inferos-Mod#5]
Can you please add a config option to disable the infinite fire resistance for the player?

**Comment by superdextor** [comment]
I'm assuming you you are referring to the infinite Fire Resistance while in Nether Survival mode. I suppose I can add an Option for that. (just watch your step)

**Comment by dmodoomsirius** [comment]
that is correct.

**Comment by dmodoomsirius** [comment]
I am currently playing the 1.10.2 version. just thought id comment before i forgot.

**Comment by superdextor** [comment]
I see, I do not write patches for 1.10.2 anymore, but once the source goes up your more than welcome to add it yourself for **PERSONAL USE ONLY**.
