### ISSUE TITLE
Ad Inferos mobs don't spawn in NetherEx biomes

### ISSUE THREAD

**Issue by LogicTechCorp** [superdextor/Ad-Inferos-Mod#7]
When Ad Inferos is installed alongside NetherEx, the Ad Inferos mobs don't spawn in NetherEx biomes. An easy fix would be to get every biome registered as a Nether biome from the BiomeDictionary and add it to the Ad Inferos mobs spawn biomes.

**Comment by superdextor** [comment]
Thank you for the report, I'll fix it in the next update. :-)
