### ISSUE TITLE
Getting Unexpected error on logging in to server

### ISSUE THREAD

**Issue by danieru-desu** [superdextor/Ad-Inferos-Mod#9]
I was travelling through world on my server, and got kicked with `java.lang.IllegalStateException Server tried to update attributes of a non-living entity (actually: EntityFlame['Flames'/731, l='MpServer', x=-870,50, y=34,00, z=-379,50])`
Since then I was not able to log in to this server, bcuz each time I connect, it kicks me again even before anything on my screen except that "dirt loading wallpaper" is getting rendered.
Crash-report is here: https://pastebin.com/TPiF7ivB
Mc version is 1.7.10, mod list is here: https://pastebin.com/FxR87X0Z
Server core is KCauldron
World zip is here: http://dropmefiles.com/EWEP7.
I've posted this here, because as I read in crash-report, the entity bugged was from Ad Infernos mod.
Please, help me(

**Comment by danieru-desu** [comment]
UPD: Stoplag, clearlag and killmobs do not help.

**Comment by superdextor** [comment]
I have no knowledge of KCauldron and I have no Idea why It would handle a Projectile as a LivingEntity. My best guess would be a plugin or another mod tried to handle the Projectile as a LivingEntity, for instance maybe it landed on a Block that damages Entities on collide but doesn't checking whether it's a LivingEntity or not.
If the Server was 1.8+ I'd say use /kill @e[type="Flames'] but another way to repair your save would be to open the World in [Mc-edit](http://www.mcedit.net) or any other external application and go to the location of the Entity, in this instance ("I don't know the world", x -870, y 34 z -379) and remove it that way, I'd also take a look around where the Flame caused the Crash to see if anything there looked like It could have instigated the Error.

**Comment by danieru-desu** [comment]
Such a shame, but I suck balls in installing mods to MCEdit (else it simply doesn't show anything at that place). 
I don't have any plugins installed, I'm not sure I have any mods that interract with projectiles (except M&B:Battlegear and Ars magica2, but there shouldn't be any custom arrows or spell projectiles at that place).
And I entered the world in singleplayer without any issues, tped there and found a nether spider sitting on these coordinates (just punched him so he fell abput 10-15 blocks down). No projectiles. No flames. No anything. And no problems with entering the world. Then I copied this world back to server and the problem expired. For about 3 mins, then the same happened again with a bit different coordinates (looks like another spider has spawned), so I had to uninstall your mod. Also it might be something wrong with Difficult Life mod, isn't it? Bcuz it modifies mob's HP and damage (and maybe "natural armor").
P.s. Config files are **exact same** on both client and server.

**Comment by superdextor** [comment]
I have never needed to Install mods Into *Mc-Edit* (didn't know that was a thing) since it doesn't flush any null ids It'll still keep/display all modded entities/blocks (textures won't display for blocks, but you can use *Mc-edit's* tile view tool to figure out what's what.) Also when you went teleported there as a Player The Flames Projectile updated and collided with a tile (Since it's a moving projectile) and despawned. (like how a snowball works.) Finally, I'm not familiar with *Difficult Life* and how it handles Server side values, but it could be triggering the issue by modifying the Projectile before It collides with a tile.

**Comment by danieru-desu** [comment]
But there shouldn't be any projectiles.
And when I've tped there w/ MCEdit, I didn't see any entities there. I thought it's being shown bcuz there are no mod installed to MCedit, so I just used entoty removing tool, but this had no effect.
And... Wtf was tht projectile? I... don't uderstand.
